export const QIAN_TAI_DAI_MA = {
  WANG_LUO: 'FRONTEND_NETWORK_ERROR',
  CHAO_SHI: 'FRONTEND_TIMEOUT',
  XIE_YI: 'FRONTEND_RESPONSE_INVALID',
  WEI_ZHI: 'FRONTEND_UNKNOWN_ERROR',
  QU_XIAO: 'FRONTEND_REQUEST_CANCELLED',
  REQUEST_PARAMETER_INVALID: 'REQUEST_PARAMETER_INVALID',
  REQUEST_MISSING_PARAMETER: 'REQUEST_MISSING_PARAMETER',
  REQUEST_BODY_INVALID: 'REQUEST_BODY_INVALID',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UPSTREAM_NETWORK_ERROR: 'UPSTREAM_NETWORK_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  UPSTREAM_TIMEOUT: 'UPSTREAM_TIMEOUT',
  DATABASE_ERROR: 'DATABASE_ERROR',
  ORIGIN_DENIED: 'ORIGIN_DENIED',
  AUTH_SMS_RATE_LIMITED: 'AUTH_SMS_RATE_LIMITED',
  AUTH_SMS_SEND_FAILED: 'AUTH_SMS_SEND_FAILED',
  AUTH_REGISTRATION_CLOSED: 'AUTH_REGISTRATION_CLOSED',
  AUTH_ACCOUNT_ALREADY_EXISTS: 'AUTH_ACCOUNT_ALREADY_EXISTS',
  AUTH_REGISTRATION_FAILED: 'AUTH_REGISTRATION_FAILED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_PASSWORD_CHANGE_FAILED: 'AUTH_PASSWORD_CHANGE_FAILED',
  AUTH_USERNAME_CHANGE_FAILED: 'AUTH_USERNAME_CHANGE_FAILED',
  AUTH_DEFAULT_GENDER_INVALID: 'AUTH_DEFAULT_GENDER_INVALID',
  AUTH_ACCOUNT_DELETION_FAILED: 'AUTH_ACCOUNT_DELETION_FAILED',
  ROLE_GENERATION_INPUT_INVALID: 'ROLE_GENERATION_INPUT_INVALID',
  ROLE_GENERATION_INITIALIZATION_FAILED: 'ROLE_GENERATION_INITIALIZATION_FAILED',
  ROLE_GENERATION_MODEL_UNAVAILABLE: 'ROLE_GENERATION_MODEL_UNAVAILABLE',
  ROLE_GENERATION_MODEL_CALL_FAILED: 'ROLE_GENERATION_MODEL_CALL_FAILED',
  ROLE_GENERATION_RESPONSE_INVALID: 'ROLE_GENERATION_RESPONSE_INVALID',
  ROLE_GENERATION_PERSISTENCE_FAILED: 'ROLE_GENERATION_PERSISTENCE_FAILED',
  JUN_SHI_ZAI_ZHI_DAO_ZHONG: 'JUN_SHI_ZAI_ZHI_DAO_ZHONG',
  JUN_SHI_CHONG_FU: 'JUN_SHI_CHONG_FU',
  WU_LIAO_TIAN_JI_LU: 'WU_LIAO_TIAN_JI_LU',
  DEPENDENCY_POSTGRES_UNAVAILABLE: 'DEPENDENCY_POSTGRES_UNAVAILABLE',
  DEPENDENCY_REDIS_UNAVAILABLE: 'DEPENDENCY_REDIS_UNAVAILABLE',
  DEPENDENCIES_UNAVAILABLE: 'DEPENDENCIES_UNAVAILABLE',
  DOCKER_STARTUP_MIGRATION_SCRIPT_MISSING: 'DOCKER_STARTUP_MIGRATION_SCRIPT_MISSING',
  DOCKER_STARTUP_MIGRATION_FAILED: 'DOCKER_STARTUP_MIGRATION_FAILED',
  DOCKER_STARTUP_REDIS_TLS_INVALID: 'DOCKER_STARTUP_REDIS_TLS_INVALID',
  DOCKER_STARTUP_REDIS_UNAVAILABLE: 'DOCKER_STARTUP_REDIS_UNAVAILABLE',
  DOCKER_STARTUP_POSTGRES_UNAVAILABLE: 'DOCKER_STARTUP_POSTGRES_UNAVAILABLE',
  DOCKER_STARTUP_MODERATION_RESOURCE_UNAVAILABLE: 'DOCKER_STARTUP_MODERATION_RESOURCE_UNAVAILABLE',
  ZHAN_JI_FEN_LEI_MING_CHENG_WU_XIAO: 'ZHAN_JI_FEN_LEI_MING_CHENG_WU_XIAO',
  ZHAN_JI_FEN_LEI_MING_CHENG_CHANG: 'ZHAN_JI_FEN_LEI_MING_CHENG_CHANG',
  ZHAN_JI_FEN_LEI_MING_CHENG_CHONG_FU: 'ZHAN_JI_FEN_LEI_MING_CHENG_CHONG_FU',
  ZHAN_JI_FEN_LEI_BIAN_GENG: 'ZHAN_JI_FEN_LEI_BIAN_GENG',
  ZHAN_JI_MO_REN_FEN_LEI_BU_NENG_SHAN_CHU: 'ZHAN_JI_MO_REN_FEN_LEI_BU_NENG_SHAN_CHU',
  ZHAN_JI_FEN_LEI_BU_CUN_ZAI: 'ZHAN_JI_FEN_LEI_BU_CUN_ZAI',
  ZHAN_JI_DANG_AN_BU_CUN_ZAI: 'ZHAN_JI_DANG_AN_BU_CUN_ZAI',
  ZHAN_JI_DANG_AN_BU_SHU_YU_FEN_LEI: 'ZHAN_JI_DANG_AN_BU_SHU_YU_FEN_LEI',
  ZHAN_JI_BU_NENG_YIDONG_DAO_DANG_QIAN_FEN_LEI: 'ZHAN_JI_BU_NENG_YIDONG_DAO_DANG_QIAN_FEN_LEI',
  ZHAN_JI_PAI_XU_ID_CHONG_FU: 'ZHAN_JI_PAI_XU_ID_CHONG_FU',
  ZHAN_JI_PAI_XU_JI_LU_BU_WU_ZHEN: 'ZHAN_JI_PAI_XU_JI_LU_BU_WU_ZHEN',
  ZHAN_JI_SHU_JU_BIAN_HUA: 'ZHAN_JI_SHU_JU_BIAN_HUA',
  ZHAN_JI_FEN_LEI_BAN_BEN_BU_HE_FA: 'ZHAN_JI_FEN_LEI_BAN_BEN_BU_HE_FA',
  ZHAN_JI_PAI_XU_CAN_SHU_BU_HE_FA: 'ZHAN_JI_PAI_XU_CAN_SHU_BU_HE_FA',
} as const

export type QianTaiDaiMa = (typeof QIAN_TAI_DAI_MA)[keyof typeof QIAN_TAI_DAI_MA]

export type QianTaiWenBenLeiXing =
  | 'qingQiu'
  | 'wangLuo'
  | 'chaoShi'
  | 'fangWen'
  | 'jianQuan'
  | 'quanXian'
  | 'ziYuan'
  | 'chongTu'
  | 'pinFan'
  | 'fuWu'
  | 'jiaoSe'
  | 'zhanJi'
  | 'tongYong'
  | 'quXiao'

/** 文本类别的穷举清单（判据守卫用：新增类别必须同时补齐影响/下一步文案，否则守卫会红） */
export const WEN_BEN_LEI_XING_QUAN_LU: readonly QianTaiWenBenLeiXing[] = [
  'qingQiu',
  'wangLuo',
  'chaoShi',
  'fangWen',
  'jianQuan',
  'quanXian',
  'ziYuan',
  'chongTu',
  'pinFan',
  'fuWu',
  'jiaoSe',
  'zhanJi',
  'tongYong',
  'quXiao',
]

const WEN_BEN_ZU: Readonly<Record<QianTaiDaiMa, QianTaiWenBenLeiXing>> = {
  FRONTEND_NETWORK_ERROR: 'wangLuo',
  FRONTEND_TIMEOUT: 'chaoShi',
  FRONTEND_RESPONSE_INVALID: 'fangWen',
  FRONTEND_UNKNOWN_ERROR: 'tongYong',
  FRONTEND_REQUEST_CANCELLED: 'quXiao',
  REQUEST_PARAMETER_INVALID: 'qingQiu',
  REQUEST_MISSING_PARAMETER: 'qingQiu',
  REQUEST_BODY_INVALID: 'qingQiu',
  PAYLOAD_TOO_LARGE: 'qingQiu',
  AUTHENTICATION_REQUIRED: 'jianQuan',
  AUTH_TOKEN_INVALID: 'jianQuan',
  PERMISSION_DENIED: 'quanXian',
  RESOURCE_NOT_FOUND: 'ziYuan',
  METHOD_NOT_ALLOWED: 'qingQiu',
  RESOURCE_CONFLICT: 'chongTu',
  RATE_LIMITED: 'pinFan',
  INTERNAL_ERROR: 'fuWu',
  UPSTREAM_NETWORK_ERROR: 'fuWu',
  SERVICE_UNAVAILABLE: 'fuWu',
  UPSTREAM_TIMEOUT: 'fuWu',
  DATABASE_ERROR: 'fuWu',
  ORIGIN_DENIED: 'quanXian',
  AUTH_SMS_RATE_LIMITED: 'pinFan',
  AUTH_SMS_SEND_FAILED: 'fuWu',
  AUTH_REGISTRATION_CLOSED: 'jianQuan',
  AUTH_ACCOUNT_ALREADY_EXISTS: 'qingQiu',
  AUTH_REGISTRATION_FAILED: 'fuWu',
  AUTH_INVALID_CREDENTIALS: 'jianQuan',
  AUTH_REFRESH_TOKEN_INVALID: 'jianQuan',
  AUTH_PASSWORD_CHANGE_FAILED: 'qingQiu',
  AUTH_USERNAME_CHANGE_FAILED: 'chongTu',
  AUTH_DEFAULT_GENDER_INVALID: 'qingQiu',
  AUTH_ACCOUNT_DELETION_FAILED: 'fuWu',
  ROLE_GENERATION_INPUT_INVALID: 'qingQiu',
  ROLE_GENERATION_INITIALIZATION_FAILED: 'jiaoSe',
  ROLE_GENERATION_MODEL_UNAVAILABLE: 'jiaoSe',
  ROLE_GENERATION_MODEL_CALL_FAILED: 'jiaoSe',
  ROLE_GENERATION_RESPONSE_INVALID: 'jiaoSe',
  ROLE_GENERATION_PERSISTENCE_FAILED: 'jiaoSe',
  JUN_SHI_ZAI_ZHI_DAO_ZHONG: 'jiaoSe',
  JUN_SHI_CHONG_FU: 'jiaoSe',
  WU_LIAO_TIAN_JI_LU: 'jiaoSe',
  DEPENDENCY_POSTGRES_UNAVAILABLE: 'fuWu',
  DEPENDENCY_REDIS_UNAVAILABLE: 'fuWu',
  DEPENDENCIES_UNAVAILABLE: 'fuWu',
  DOCKER_STARTUP_MIGRATION_SCRIPT_MISSING: 'fuWu',
  DOCKER_STARTUP_MIGRATION_FAILED: 'fuWu',
  DOCKER_STARTUP_REDIS_TLS_INVALID: 'fuWu',
  DOCKER_STARTUP_REDIS_UNAVAILABLE: 'fuWu',
  DOCKER_STARTUP_POSTGRES_UNAVAILABLE: 'fuWu',
  DOCKER_STARTUP_MODERATION_RESOURCE_UNAVAILABLE: 'fuWu',
  ZHAN_JI_FEN_LEI_MING_CHENG_WU_XIAO: 'zhanJi',
  ZHAN_JI_FEN_LEI_MING_CHENG_CHANG: 'zhanJi',
  ZHAN_JI_FEN_LEI_MING_CHENG_CHONG_FU: 'zhanJi',
  ZHAN_JI_FEN_LEI_BIAN_GENG: 'zhanJi',
  ZHAN_JI_MO_REN_FEN_LEI_BU_NENG_SHAN_CHU: 'zhanJi',
  ZHAN_JI_FEN_LEI_BU_CUN_ZAI: 'zhanJi',
  ZHAN_JI_DANG_AN_BU_CUN_ZAI: 'zhanJi',
  ZHAN_JI_DANG_AN_BU_SHU_YU_FEN_LEI: 'zhanJi',
  ZHAN_JI_BU_NENG_YIDONG_DAO_DANG_QIAN_FEN_LEI: 'zhanJi',
  ZHAN_JI_PAI_XU_ID_CHONG_FU: 'zhanJi',
  ZHAN_JI_PAI_XU_JI_LU_BU_WU_ZHEN: 'zhanJi',
  ZHAN_JI_SHU_JU_BIAN_HUA: 'zhanJi',
  ZHAN_JI_FEN_LEI_BAN_BEN_BU_HE_FA: 'zhanJi',
  ZHAN_JI_PAI_XU_CAN_SHU_BU_HE_FA: 'zhanJi',
}

const JIU_DAI_MA_BIAN_SHE: Readonly<Record<string, QianTaiDaiMa>> = {
  CAN_SHU_CUO_WU: QIAN_TAI_DAI_MA.REQUEST_PARAMETER_INVALID,
  WEI_SHOU_QUAN: QIAN_TAI_DAI_MA.AUTHENTICATION_REQUIRED,
  LING_PAI_WU_XIAO: QIAN_TAI_DAI_MA.AUTH_TOKEN_INVALID,
  WU_GUAN_LI_QUAN_XIAN: QIAN_TAI_DAI_MA.PERMISSION_DENIED,
  WEI_ZHAO_DAO: QIAN_TAI_DAI_MA.RESOURCE_NOT_FOUND,
}

const KE_CHONG_SHI_DAI_MA = new Set<QianTaiDaiMa>([
  QIAN_TAI_DAI_MA.WANG_LUO,
  QIAN_TAI_DAI_MA.CHAO_SHI,
  QIAN_TAI_DAI_MA.XIE_YI,
  QIAN_TAI_DAI_MA.RATE_LIMITED,
  QIAN_TAI_DAI_MA.UPSTREAM_NETWORK_ERROR,
  QIAN_TAI_DAI_MA.SERVICE_UNAVAILABLE,
  QIAN_TAI_DAI_MA.UPSTREAM_TIMEOUT,
  QIAN_TAI_DAI_MA.DATABASE_ERROR,
  QIAN_TAI_DAI_MA.INTERNAL_ERROR,
  QIAN_TAI_DAI_MA.AUTH_SMS_RATE_LIMITED,
  QIAN_TAI_DAI_MA.AUTH_SMS_SEND_FAILED,
  QIAN_TAI_DAI_MA.AUTH_REGISTRATION_FAILED,
  QIAN_TAI_DAI_MA.ROLE_GENERATION_MODEL_UNAVAILABLE,
  QIAN_TAI_DAI_MA.ROLE_GENERATION_MODEL_CALL_FAILED,
  QIAN_TAI_DAI_MA.ROLE_GENERATION_RESPONSE_INVALID,
  QIAN_TAI_DAI_MA.ROLE_GENERATION_PERSISTENCE_FAILED,
  QIAN_TAI_DAI_MA.JUN_SHI_ZAI_ZHI_DAO_ZHONG,
  QIAN_TAI_DAI_MA.DEPENDENCY_POSTGRES_UNAVAILABLE,
  QIAN_TAI_DAI_MA.DEPENDENCY_REDIS_UNAVAILABLE,
  QIAN_TAI_DAI_MA.DEPENDENCIES_UNAVAILABLE,
  QIAN_TAI_DAI_MA.DOCKER_STARTUP_MIGRATION_FAILED,
  QIAN_TAI_DAI_MA.DOCKER_STARTUP_REDIS_UNAVAILABLE,
  QIAN_TAI_DAI_MA.DOCKER_STARTUP_POSTGRES_UNAVAILABLE,
  QIAN_TAI_DAI_MA.WEI_ZHI,
])

export function guiYiQianTaiDaiMa(zhi: unknown): QianTaiDaiMa | null {
  if (typeof zhi !== 'string') return null
  if (Object.hasOwn(WEN_BEN_ZU, zhi)) return zhi as QianTaiDaiMa
  return JIU_DAI_MA_BIAN_SHE[zhi] || null
}

export function huoQuWenBenLeiXing(daiMa: QianTaiDaiMa): QianTaiWenBenLeiXing {
  return WEN_BEN_ZU[daiMa]
}

export function moRenKeChongShi(daiMa: QianTaiDaiMa): boolean {
  return KE_CHONG_SHI_DAI_MA.has(daiMa)
}

export function daiMaHuoQuTongYongDaiMa(zhuangTai: number): QianTaiDaiMa | null {
  const xianRong: Readonly<Record<number, QianTaiDaiMa>> = {
    400: QIAN_TAI_DAI_MA.REQUEST_PARAMETER_INVALID,
    401: QIAN_TAI_DAI_MA.AUTHENTICATION_REQUIRED,
    403: QIAN_TAI_DAI_MA.PERMISSION_DENIED,
    404: QIAN_TAI_DAI_MA.RESOURCE_NOT_FOUND,
    405: QIAN_TAI_DAI_MA.METHOD_NOT_ALLOWED,
    409: QIAN_TAI_DAI_MA.RESOURCE_CONFLICT,
    413: QIAN_TAI_DAI_MA.PAYLOAD_TOO_LARGE,
    422: QIAN_TAI_DAI_MA.REQUEST_PARAMETER_INVALID,
    429: QIAN_TAI_DAI_MA.RATE_LIMITED,
    500: QIAN_TAI_DAI_MA.INTERNAL_ERROR,
    502: QIAN_TAI_DAI_MA.UPSTREAM_NETWORK_ERROR,
    503: QIAN_TAI_DAI_MA.SERVICE_UNAVAILABLE,
    504: QIAN_TAI_DAI_MA.UPSTREAM_TIMEOUT,
  }
  return xianRong[zhuangTai] || null
}
