-- 恢复 记忆 表最小存根（被测试/代码引用，仅作存根）
-- 对话摘要表同理

CREATE TABLE IF NOT EXISTS "记忆" (
    "ID" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "用户ID" UUID NOT NULL REFERENCES "用户"("ID") ON DELETE CASCADE,
    "角色ID" UUID NOT NULL REFERENCES "角色"("ID") ON DELETE CASCADE,
    "内容" TEXT NOT NULL,
    "重要度" SMALLINT NOT NULL DEFAULT 0,
    "创建时间" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_记忆_用户ID_角色ID ON "记忆" ("用户ID", "角色ID");

CREATE TABLE IF NOT EXISTS "对话摘要" (
    "ID" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "用户ID" UUID NOT NULL REFERENCES "用户"("ID") ON DELETE CASCADE,
    "角色ID" UUID NOT NULL REFERENCES "角色"("ID") ON DELETE CASCADE,
    "摘要" TEXT NOT NULL,
    "创建时间" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_对话摘要_用户ID_角色ID ON "对话摘要" ("用户ID", "角色ID");