import { huoQuFanYi } from './translations'

export const CUO_WU_DAI_MA = {
  REQUEST_PARAMETER_INVALID: 'REQUEST_PARAMETER_INVALID',
  REQUEST_MISSING_PARAMETER: 'REQUEST_MISSING_PARAMETER',
  REQUEST_BODY_INVALID: 'REQUEST_BODY_INVALID',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UPSTREAM_NETWORK_ERROR: 'UPSTREAM_NETWORK_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  UPSTREAM_TIMEOUT: 'UPSTREAM_TIMEOUT',
  DATABASE_ERROR: 'DATABASE_ERROR',
  ORIGIN_DENIED: 'ORIGIN_DENIED',
  AUTH_SMS_RATE_LIMITED: 'AUTH_SMS_RATE_LIMITED',
  AUTH_SMS_SEND_FAILED: 'AUTH_SMS_SEND_FAILED',
  AUTH_REGISTRATION_CLOSED: 'AUTH_REGISTRATION_CLOSED',
  AUTH_ACCOUNT_ALREADY_EXISTS: 'AUTH_ACCOUNT_ALREADY_EXISTS',
  AUTH_REGISTRATION_FAILED: 'AUTH_REGISTRATION_FAILED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_PASSWORD_CHANGE_FAILED: 'AUTH_PASSWORD_CHANGE_FAILED',
  AUTH_USERNAME_CHANGE_FAILED: 'AUTH_USERNAME_CHANGE_FAILED',
  AUTH_DEFAULT_GENDER_INVALID: 'AUTH_DEFAULT_GENDER_INVALID',
  AUTH_ACCOUNT_DELETION_FAILED: 'AUTH_ACCOUNT_DELETION_FAILED',
  ROLE_GENERATION_INPUT_INVALID: 'ROLE_GENERATION_INPUT_INVALID',
  ROLE_GENERATION_INITIALIZATION_FAILED: 'ROLE_GENERATION_INITIALIZATION_FAILED',
  ROLE_GENERATION_MODEL_UNAVAILABLE: 'ROLE_GENERATION_MODEL_UNAVAILABLE',
  ROLE_GENERATION_MODEL_CALL_FAILED: 'ROLE_GENERATION_MODEL_CALL_FAILED',
  ROLE_GENERATION_RESPONSE_INVALID: 'ROLE_GENERATION_RESPONSE_INVALID',
  ROLE_GENERATION_PERSISTENCE_FAILED: 'ROLE_GENERATION_PERSISTENCE_FAILED',
  DEPENDENCY_POSTGRES_UNAVAILABLE: 'DEPENDENCY_POSTGRES_UNAVAILABLE',
  DEPENDENCY_REDIS_UNAVAILABLE: 'DEPENDENCY_REDIS_UNAVAILABLE',
  DEPENDENCIES_UNAVAILABLE: 'DEPENDENCIES_UNAVAILABLE',
  DOCKER_STARTUP_MIGRATION_SCRIPT_MISSING: 'DOCKER_STARTUP_MIGRATION_SCRIPT_MISSING',
  DOCKER_STARTUP_MIGRATION_FAILED: 'DOCKER_STARTUP_MIGRATION_FAILED',
  DOCKER_STARTUP_REDIS_TLS_INVALID: 'DOCKER_STARTUP_REDIS_TLS_INVALID',
  DOCKER_STARTUP_REDIS_UNAVAILABLE: 'DOCKER_STARTUP_REDIS_UNAVAILABLE',
  DOCKER_STARTUP_POSTGRES_UNAVAILABLE: 'DOCKER_STARTUP_POSTGRES_UNAVAILABLE',
  DOCKER_STARTUP_MODERATION_RESOURCE_UNAVAILABLE: 'DOCKER_STARTUP_MODERATION_RESOURCE_UNAVAILABLE',
  ZHAN_JI_FEN_LEI_MING_CHENG_WU_XIAO: 'ZHAN_JI_FEN_LEI_MING_CHENG_WU_XIAO',
  ZHAN_JI_FEN_LEI_MING_CHENG_CHANG: 'ZHAN_JI_FEN_LEI_MING_CHENG_CHANG',
  ZHAN_JI_FEN_LEI_MING_CHENG_CHONG_FU: 'ZHAN_JI_FEN_LEI_MING_CHENG_CHONG_FU',
  ZHAN_JI_FEN_LEI_BIAN_GENG: 'ZHAN_JI_FEN_LEI_BIAN_GENG',
  ZHAN_JI_MO_REN_FEN_LEI_BU_NENG_SHAN_CHU: 'ZHAN_JI_MO_REN_FEN_LEI_BU_NENG_SHAN_CHU',
  ZHAN_JI_FEN_LEI_BU_CUN_ZAI: 'ZHAN_JI_FEN_LEI_BU_CUN_ZAI',
  ZHAN_JI_DANG_AN_BU_CUN_ZAI: 'ZHAN_JI_DANG_AN_BU_CUN_ZAI',
  ZHAN_JI_DANG_AN_BU_SHU_YU_FEN_LEI: 'ZHAN_JI_DANG_AN_BU_SHU_YU_FEN_LEI',
  ZHAN_JI_BU_NENG_YIDONG_DAO_DANG_QIAN_FEN_LEI: 'ZHAN_JI_BU_NENG_YIDONG_DAO_DANG_QIAN_FEN_LEI',
  ZHAN_JI_PAI_XU_ID_CHONG_FU: 'ZHAN_JI_PAI_XU_ID_CHONG_FU',
  ZHAN_JI_PAI_XU_JI_LU_BU_WU_ZHEN: 'ZHAN_JI_PAI_XU_JI_LU_BU_WU_ZHEN',
  ZHAN_JI_SHU_JU_BIAN_HUA: 'ZHAN_JI_SHU_JU_BIAN_HUA',
  ZHAN_JI_FEN_LEI_BAN_BEN_BU_HE_FA: 'ZHAN_JI_FEN_LEI_BAN_BEN_BU_HE_FA',
  ZHAN_JI_PAI_XU_CAN_SHU_BU_HE_FA: 'ZHAN_JI_PAI_XU_CAN_SHU_BU_HE_FA',
} as const

export const JIU_DAI_MA = {
  WEI_SHOU_QUAN: 'WEI_SHOU_QUAN',
  WU_GUAN_LI_QUAN_XIAN: 'WU_GUAN_LI_QUAN_XIAN',
} as const

export type CuoWuDaiMa = typeof CUO_WU_DAI_MA[keyof typeof CUO_WU_DAI_MA]
export type CuoWuJieMian = string
export type ZhanJiFenLeiCuoWuDaiMa = Extract<CuoWuDaiMa, `ZHAN_JI_${string}`>
export type JiaoSeShengChengCuoWuDaiMa = Extract<CuoWuDaiMa, `ROLE_GENERATION_${string}`>

export interface CuoWuXianRong {
  code: CuoWuDaiMa
  jieMian: CuoWuJieMian
  httpStatus: number
  message: string
  retryable: boolean
  retryAfterMs?: number
}

const xianRongBiao: Record<CuoWuDaiMa, Omit<CuoWuXianRong, 'message'>> = {
  [CUO_WU_DAI_MA.REQUEST_PARAMETER_INVALID]: { code: CUO_WU_DAI_MA.REQUEST_PARAMETER_INVALID, jieMian: 'tongYong', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.REQUEST_MISSING_PARAMETER]: { code: CUO_WU_DAI_MA.REQUEST_MISSING_PARAMETER, jieMian: 'tongYong', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.REQUEST_BODY_INVALID]: { code: CUO_WU_DAI_MA.REQUEST_BODY_INVALID, jieMian: 'tongYong', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.PAYLOAD_TOO_LARGE]: { code: CUO_WU_DAI_MA.PAYLOAD_TOO_LARGE, jieMian: 'tongYong', httpStatus: 413, retryable: false },
  [CUO_WU_DAI_MA.AUTHENTICATION_REQUIRED]: { code: CUO_WU_DAI_MA.AUTHENTICATION_REQUIRED, jieMian: 'tongYong', httpStatus: 401, retryable: false },
  [CUO_WU_DAI_MA.AUTH_TOKEN_INVALID]: { code: CUO_WU_DAI_MA.AUTH_TOKEN_INVALID, jieMian: 'renZheng', httpStatus: 401, retryable: false },
  [CUO_WU_DAI_MA.PERMISSION_DENIED]: { code: CUO_WU_DAI_MA.PERMISSION_DENIED, jieMian: 'guanLiYuan', httpStatus: 403, retryable: false },
  [CUO_WU_DAI_MA.RESOURCE_NOT_FOUND]: { code: CUO_WU_DAI_MA.RESOURCE_NOT_FOUND, jieMian: 'tongYong', httpStatus: 404, retryable: false },
  [CUO_WU_DAI_MA.METHOD_NOT_ALLOWED]: { code: CUO_WU_DAI_MA.METHOD_NOT_ALLOWED, jieMian: 'tongYong', httpStatus: 405, retryable: false },
  [CUO_WU_DAI_MA.RESOURCE_CONFLICT]: { code: CUO_WU_DAI_MA.RESOURCE_CONFLICT, jieMian: 'tongYong', httpStatus: 409, retryable: false },
  [CUO_WU_DAI_MA.RATE_LIMITED]: { code: CUO_WU_DAI_MA.RATE_LIMITED, jieMian: 'tongYong', httpStatus: 429, retryable: true, retryAfterMs: 1000 },
  [CUO_WU_DAI_MA.INTERNAL_ERROR]: { code: CUO_WU_DAI_MA.INTERNAL_ERROR, jieMian: 'tongYong', httpStatus: 500, retryable: false },
  [CUO_WU_DAI_MA.UPSTREAM_NETWORK_ERROR]: { code: CUO_WU_DAI_MA.UPSTREAM_NETWORK_ERROR, jieMian: 'tongYong', httpStatus: 502, retryable: true },
  [CUO_WU_DAI_MA.SERVICE_UNAVAILABLE]: { code: CUO_WU_DAI_MA.SERVICE_UNAVAILABLE, jieMian: 'tongYong', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.UPSTREAM_TIMEOUT]: { code: CUO_WU_DAI_MA.UPSTREAM_TIMEOUT, jieMian: 'tongYong', httpStatus: 504, retryable: true },
  [CUO_WU_DAI_MA.DATABASE_ERROR]: { code: CUO_WU_DAI_MA.DATABASE_ERROR, jieMian: 'tongYong', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.ORIGIN_DENIED]: { code: CUO_WU_DAI_MA.ORIGIN_DENIED, jieMian: 'tongYong', httpStatus: 403, retryable: false },
  [CUO_WU_DAI_MA.AUTH_SMS_RATE_LIMITED]: { code: CUO_WU_DAI_MA.AUTH_SMS_RATE_LIMITED, jieMian: 'renZheng', httpStatus: 429, retryable: true, retryAfterMs: 60000 },
  [CUO_WU_DAI_MA.AUTH_SMS_SEND_FAILED]: { code: CUO_WU_DAI_MA.AUTH_SMS_SEND_FAILED, jieMian: 'renZheng', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.AUTH_REGISTRATION_CLOSED]: { code: CUO_WU_DAI_MA.AUTH_REGISTRATION_CLOSED, jieMian: 'renZheng', httpStatus: 429, retryable: false },
  [CUO_WU_DAI_MA.AUTH_ACCOUNT_ALREADY_EXISTS]: { code: CUO_WU_DAI_MA.AUTH_ACCOUNT_ALREADY_EXISTS, jieMian: 'renZheng', httpStatus: 409, retryable: false },
  [CUO_WU_DAI_MA.AUTH_REGISTRATION_FAILED]: { code: CUO_WU_DAI_MA.AUTH_REGISTRATION_FAILED, jieMian: 'renZheng', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.AUTH_INVALID_CREDENTIALS]: { code: CUO_WU_DAI_MA.AUTH_INVALID_CREDENTIALS, jieMian: 'renZheng', httpStatus: 401, retryable: false },
  [CUO_WU_DAI_MA.AUTH_REFRESH_TOKEN_INVALID]: { code: CUO_WU_DAI_MA.AUTH_REFRESH_TOKEN_INVALID, jieMian: 'renZheng', httpStatus: 401, retryable: false },
  [CUO_WU_DAI_MA.AUTH_PASSWORD_CHANGE_FAILED]: { code: CUO_WU_DAI_MA.AUTH_PASSWORD_CHANGE_FAILED, jieMian: 'renZheng', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.AUTH_USERNAME_CHANGE_FAILED]: { code: CUO_WU_DAI_MA.AUTH_USERNAME_CHANGE_FAILED, jieMian: 'renZheng', httpStatus: 409, retryable: false },
  [CUO_WU_DAI_MA.AUTH_DEFAULT_GENDER_INVALID]: { code: CUO_WU_DAI_MA.AUTH_DEFAULT_GENDER_INVALID, jieMian: 'anQuan', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.AUTH_ACCOUNT_DELETION_FAILED]: { code: CUO_WU_DAI_MA.AUTH_ACCOUNT_DELETION_FAILED, jieMian: 'renZheng', httpStatus: 500, retryable: false },
  [CUO_WU_DAI_MA.ROLE_GENERATION_INPUT_INVALID]: { code: CUO_WU_DAI_MA.ROLE_GENERATION_INPUT_INVALID, jieMian: 'jiaoSe', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.ROLE_GENERATION_INITIALIZATION_FAILED]: { code: CUO_WU_DAI_MA.ROLE_GENERATION_INITIALIZATION_FAILED, jieMian: 'jiaoSe', httpStatus: 500, retryable: false },
  [CUO_WU_DAI_MA.ROLE_GENERATION_MODEL_UNAVAILABLE]: { code: CUO_WU_DAI_MA.ROLE_GENERATION_MODEL_UNAVAILABLE, jieMian: 'jiaoSe', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.ROLE_GENERATION_MODEL_CALL_FAILED]: { code: CUO_WU_DAI_MA.ROLE_GENERATION_MODEL_CALL_FAILED, jieMian: 'jiaoSe', httpStatus: 502, retryable: true },
  [CUO_WU_DAI_MA.ROLE_GENERATION_RESPONSE_INVALID]: { code: CUO_WU_DAI_MA.ROLE_GENERATION_RESPONSE_INVALID, jieMian: 'jiaoSe', httpStatus: 502, retryable: true },
  [CUO_WU_DAI_MA.ROLE_GENERATION_PERSISTENCE_FAILED]: { code: CUO_WU_DAI_MA.ROLE_GENERATION_PERSISTENCE_FAILED, jieMian: 'jiaoSe', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.DEPENDENCY_POSTGRES_UNAVAILABLE]: { code: CUO_WU_DAI_MA.DEPENDENCY_POSTGRES_UNAVAILABLE, jieMian: 'tongYong', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.DEPENDENCY_REDIS_UNAVAILABLE]: { code: CUO_WU_DAI_MA.DEPENDENCY_REDIS_UNAVAILABLE, jieMian: 'tongYong', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.DEPENDENCIES_UNAVAILABLE]: { code: CUO_WU_DAI_MA.DEPENDENCIES_UNAVAILABLE, jieMian: 'tongYong', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.DOCKER_STARTUP_MIGRATION_SCRIPT_MISSING]: { code: CUO_WU_DAI_MA.DOCKER_STARTUP_MIGRATION_SCRIPT_MISSING, jieMian: 'qiDong', httpStatus: 503, retryable: false },
  [CUO_WU_DAI_MA.DOCKER_STARTUP_MIGRATION_FAILED]: { code: CUO_WU_DAI_MA.DOCKER_STARTUP_MIGRATION_FAILED, jieMian: 'qiDong', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.DOCKER_STARTUP_REDIS_TLS_INVALID]: { code: CUO_WU_DAI_MA.DOCKER_STARTUP_REDIS_TLS_INVALID, jieMian: 'qiDong', httpStatus: 503, retryable: false },
  [CUO_WU_DAI_MA.DOCKER_STARTUP_REDIS_UNAVAILABLE]: { code: CUO_WU_DAI_MA.DOCKER_STARTUP_REDIS_UNAVAILABLE, jieMian: 'qiDong', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.DOCKER_STARTUP_POSTGRES_UNAVAILABLE]: { code: CUO_WU_DAI_MA.DOCKER_STARTUP_POSTGRES_UNAVAILABLE, jieMian: 'qiDong', httpStatus: 503, retryable: true },
  [CUO_WU_DAI_MA.DOCKER_STARTUP_MODERATION_RESOURCE_UNAVAILABLE]: { code: CUO_WU_DAI_MA.DOCKER_STARTUP_MODERATION_RESOURCE_UNAVAILABLE, jieMian: 'qiDong', httpStatus: 503, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_MING_CHENG_WU_XIAO]: { code: CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_MING_CHENG_WU_XIAO, jieMian: 'zhanJi', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_MING_CHENG_CHANG]: { code: CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_MING_CHENG_CHANG, jieMian: 'zhanJi', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_MING_CHENG_CHONG_FU]: { code: CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_MING_CHENG_CHONG_FU, jieMian: 'zhanJi', httpStatus: 409, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_BIAN_GENG]: { code: CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_BIAN_GENG, jieMian: 'zhanJi', httpStatus: 409, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_MO_REN_FEN_LEI_BU_NENG_SHAN_CHU]: { code: CUO_WU_DAI_MA.ZHAN_JI_MO_REN_FEN_LEI_BU_NENG_SHAN_CHU, jieMian: 'zhanJi', httpStatus: 409, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_BU_CUN_ZAI]: { code: CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_BU_CUN_ZAI, jieMian: 'zhanJi', httpStatus: 404, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_DANG_AN_BU_CUN_ZAI]: { code: CUO_WU_DAI_MA.ZHAN_JI_DANG_AN_BU_CUN_ZAI, jieMian: 'zhanJi', httpStatus: 404, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_DANG_AN_BU_SHU_YU_FEN_LEI]: { code: CUO_WU_DAI_MA.ZHAN_JI_DANG_AN_BU_SHU_YU_FEN_LEI, jieMian: 'zhanJi', httpStatus: 409, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_BU_NENG_YIDONG_DAO_DANG_QIAN_FEN_LEI]: { code: CUO_WU_DAI_MA.ZHAN_JI_BU_NENG_YIDONG_DAO_DANG_QIAN_FEN_LEI, jieMian: 'zhanJi', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_PAI_XU_ID_CHONG_FU]: { code: CUO_WU_DAI_MA.ZHAN_JI_PAI_XU_ID_CHONG_FU, jieMian: 'zhanJi', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_PAI_XU_JI_LU_BU_WU_ZHEN]: { code: CUO_WU_DAI_MA.ZHAN_JI_PAI_XU_JI_LU_BU_WU_ZHEN, jieMian: 'zhanJi', httpStatus: 409, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_SHU_JU_BIAN_HUA]: { code: CUO_WU_DAI_MA.ZHAN_JI_SHU_JU_BIAN_HUA, jieMian: 'zhanJi', httpStatus: 409, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_BAN_BEN_BU_HE_FA]: { code: CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_BAN_BEN_BU_HE_FA, jieMian: 'zhanJi', httpStatus: 400, retryable: false },
  [CUO_WU_DAI_MA.ZHAN_JI_PAI_XU_CAN_SHU_BU_HE_FA]: { code: CUO_WU_DAI_MA.ZHAN_JI_PAI_XU_CAN_SHU_BU_HE_FA, jieMian: 'zhanJi', httpStatus: 400, retryable: false },
}

const fanYiJianBiao: Record<CuoWuDaiMa, string> = {
  [CUO_WU_DAI_MA.REQUEST_PARAMETER_INVALID]: 'canShuBuHeFa',
  [CUO_WU_DAI_MA.REQUEST_MISSING_PARAMETER]: 'queShaoCanShu',
  [CUO_WU_DAI_MA.REQUEST_BODY_INVALID]: 'canShuBuHeFa',
  [CUO_WU_DAI_MA.PAYLOAD_TOO_LARGE]: 'qingQiuNeiRongGuoDa',
  [CUO_WU_DAI_MA.AUTHENTICATION_REQUIRED]: 'weiShouQuan',
  [CUO_WU_DAI_MA.AUTH_TOKEN_INVALID]: 'lingPaiWuXiao',
  [CUO_WU_DAI_MA.PERMISSION_DENIED]: 'wuGuanLiQuanXian',
  [CUO_WU_DAI_MA.RESOURCE_NOT_FOUND]: 'ziYuanBuCunZai',
  [CUO_WU_DAI_MA.METHOD_NOT_ALLOWED]: 'fangFaBuYunXu',
  [CUO_WU_DAI_MA.RESOURCE_CONFLICT]: 'ziYuanChongTu',
  [CUO_WU_DAI_MA.RATE_LIMITED]: 'caoZuoPinFan',
  [CUO_WU_DAI_MA.INTERNAL_ERROR]: 'fuWuQiNeiBuCuoWu',
  [CUO_WU_DAI_MA.UPSTREAM_NETWORK_ERROR]: 'waiBuFuWuWuXianZhi',
  [CUO_WU_DAI_MA.SERVICE_UNAVAILABLE]: 'fuWuQiWeiBeiHouXu',
  [CUO_WU_DAI_MA.UPSTREAM_TIMEOUT]: 'fuFuWuWaiXianZhi',
  [CUO_WU_DAI_MA.DATABASE_ERROR]: 'shuJuKuWeiBeiHouXu',
  [CUO_WU_DAI_MA.ORIGIN_DENIED]: 'yuanLaiWeiBeiJieShou',
  [CUO_WU_DAI_MA.AUTH_SMS_RATE_LIMITED]: 'faSongYanZhengMaPinFan',
  [CUO_WU_DAI_MA.AUTH_SMS_SEND_FAILED]: 'faSongYanZhengMaFuWuWuXianZhi',
  [CUO_WU_DAI_MA.AUTH_REGISTRATION_CLOSED]: 'tiYanBanManYuan',
  [CUO_WU_DAI_MA.AUTH_ACCOUNT_ALREADY_EXISTS]: 'shouJiHaoYiZhuCe',
  [CUO_WU_DAI_MA.AUTH_REGISTRATION_FAILED]: 'zhuCeFuWuWuXianZhi',
  [CUO_WU_DAI_MA.AUTH_INVALID_CREDENTIALS]: 'zhangHaoHuoMiMaCuoWu',
  [CUO_WU_DAI_MA.AUTH_REFRESH_TOKEN_INVALID]: 'lingPaiWuXiao',
  [CUO_WU_DAI_MA.AUTH_PASSWORD_CHANGE_FAILED]: 'xiuGaiMiMaShiBai',
  [CUO_WU_DAI_MA.AUTH_USERNAME_CHANGE_FAILED]: 'xiuGaiYongHuMingShiBai',
  [CUO_WU_DAI_MA.AUTH_DEFAULT_GENDER_INVALID]: 'shenFenBuHeFa',
  [CUO_WU_DAI_MA.AUTH_ACCOUNT_DELETION_FAILED]: 'zhuXiaoShiBai',
  [CUO_WU_DAI_MA.ROLE_GENERATION_INPUT_INVALID]: 'shengChengCanShuBuHeFa',
  [CUO_WU_DAI_MA.ROLE_GENERATION_INITIALIZATION_FAILED]: 'shengChengChuShiShiBai',
  [CUO_WU_DAI_MA.ROLE_GENERATION_MODEL_UNAVAILABLE]: 'shengChengMoXingFuWuWuXianZhi',
  [CUO_WU_DAI_MA.ROLE_GENERATION_MODEL_CALL_FAILED]: 'shengChengMoXingFuWuWuXianZhi',
  [CUO_WU_DAI_MA.ROLE_GENERATION_RESPONSE_INVALID]: 'shengChengMoXingHuiFuBuHeFa',
  [CUO_WU_DAI_MA.ROLE_GENERATION_PERSISTENCE_FAILED]: 'baoCunJiaoSeShiBai',
  [CUO_WU_DAI_MA.DEPENDENCY_POSTGRES_UNAVAILABLE]: 'shuJuKuWeiBeiHouXu',
  [CUO_WU_DAI_MA.DEPENDENCY_REDIS_UNAVAILABLE]: 'huanCunWeiBeiHouXu',
  [CUO_WU_DAI_MA.DEPENDENCIES_UNAVAILABLE]: 'yiZhiXingFuWuWuXianZhi',
  [CUO_WU_DAI_MA.DOCKER_STARTUP_MIGRATION_SCRIPT_MISSING]: 'jiaoBenBuWanZheng',
  [CUO_WU_DAI_MA.DOCKER_STARTUP_MIGRATION_FAILED]: 'yiJuWeiFaWanCheng',
  [CUO_WU_DAI_MA.DOCKER_STARTUP_REDIS_TLS_INVALID]: 'huanCunJiaYuBuAnQuan',
  [CUO_WU_DAI_MA.DOCKER_STARTUP_REDIS_UNAVAILABLE]: 'qiDongHuanCunYiBuKeYong',
  [CUO_WU_DAI_MA.DOCKER_STARTUP_POSTGRES_UNAVAILABLE]: 'qiDongShuJuKuYiBuKeYong',
  [CUO_WU_DAI_MA.DOCKER_STARTUP_MODERATION_RESOURCE_UNAVAILABLE]: 'shenHeZiDuanKuBuKeYong',
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_MING_CHENG_WU_XIAO]: 'fenLeiMingChengBuNengWeiKong',
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_MING_CHENG_CHANG]: 'fenLeiMingChengTaiChang',
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_MING_CHENG_CHONG_FU]: 'fenLeiMingChengYiCunZai',
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_BIAN_GENG]: 'fenLeiShuJuYiBianHua',
  [CUO_WU_DAI_MA.ZHAN_JI_MO_REN_FEN_LEI_BU_NENG_SHAN_CHU]: 'moRenFenLeiBuNengShanChu',
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_BU_CUN_ZAI]: 'fenLeiBuCunZai',
  [CUO_WU_DAI_MA.ZHAN_JI_DANG_AN_BU_CUN_ZAI]: 'dangAnBuCunZai',
  [CUO_WU_DAI_MA.ZHAN_JI_DANG_AN_BU_SHU_YU_FEN_LEI]: 'dangAnBuShuYuFenLei',
  [CUO_WU_DAI_MA.ZHAN_JI_BU_NENG_YIDONG_DAO_DANG_QIAN_FEN_LEI]: 'buNengYiDongDaoDangQianFenLei',
  [CUO_WU_DAI_MA.ZHAN_JI_PAI_XU_ID_CHONG_FU]: 'paiXuIDChongFu',
  [CUO_WU_DAI_MA.ZHAN_JI_PAI_XU_JI_LU_BU_WU_ZHEN]: 'paiXuBiXuBaoHanFenLeiQuanBuKeJianZhanJi',
  [CUO_WU_DAI_MA.ZHAN_JI_SHU_JU_BIAN_HUA]: 'fenLeiShuJuYiBianHua',
  [CUO_WU_DAI_MA.ZHAN_JI_FEN_LEI_BAN_BEN_BU_HE_FA]: 'fenLeiShuJuYiBianHua',
  [CUO_WU_DAI_MA.ZHAN_JI_PAI_XU_CAN_SHU_BU_HE_FA]: 'paiXuCanShuBuHeFa',
}

export const dengLiCuoWuXianRongLieBiao = Object.freeze(
  Object.keys(xianRongBiao) as CuoWuDaiMa[],
)

export function shiCuoWuDaiMa(zhi: unknown): zhi is CuoWuDaiMa {
  return typeof zhi === 'string' && Object.hasOwn(xianRongBiao, zhi)
}

export function huoQuCuoWuXianRong(daiMa: CuoWuDaiMa): CuoWuXianRong {
  const xianRong = xianRongBiao[daiMa]
  const fanYi = (huoQuFanYi as (jieMian: string, jian: string) => string)(
    xianRong.jieMian,
    fanYiJianBiao[daiMa],
  )
  return { ...xianRong, message: fanYi }
}

export class YingYongCuoWu extends Error {
  constructor(public readonly code: CuoWuDaiMa, cause?: unknown) {
    super(code)
    this.name = 'YingYongCuoWu'
    if (cause !== undefined) this.cause = cause
  }
}

export class JiaoSeShengChengCuoWu extends YingYongCuoWu {
  constructor(code: JiaoSeShengChengCuoWuDaiMa, cause?: unknown) {
    super(code, cause)
    this.name = 'JiaoSeShengChengCuoWu'
  }
}

const jiuDaiMaBianShe: Readonly<Record<string, CuoWuDaiMa>> = {
  CAN_SHU_CUO_WU: CUO_WU_DAI_MA.REQUEST_PARAMETER_INVALID,
  WEI_SHOU_QUAN: CUO_WU_DAI_MA.AUTHENTICATION_REQUIRED,
  LING_PAI_WU_XIAO: CUO_WU_DAI_MA.AUTH_TOKEN_INVALID,
  WU_GUAN_LI_QUAN_XIAN: CUO_WU_DAI_MA.PERMISSION_DENIED,
  WEI_ZHAO_DAO: CUO_WU_DAI_MA.RESOURCE_NOT_FOUND,
}

export function zhuanHuanJiuDaiMa(zhi: unknown): CuoWuDaiMa | null {
  if (shiCuoWuDaiMa(zhi)) return zhi
  if (typeof zhi !== 'string') return null
  return jiuDaiMaBianShe[zhi] || null
}

export function daiMaHuoQuZhuangTaiMa(zhi: unknown): CuoWuDaiMa {
  if (shiCuoWuDaiMa(zhi)) return zhi
  if (zhi === 400) return CUO_WU_DAI_MA.REQUEST_PARAMETER_INVALID
  if (zhi === 401) return CUO_WU_DAI_MA.AUTHENTICATION_REQUIRED
  if (zhi === 403) return CUO_WU_DAI_MA.PERMISSION_DENIED
  if (zhi === 404) return CUO_WU_DAI_MA.RESOURCE_NOT_FOUND
  if (zhi === 405) return CUO_WU_DAI_MA.METHOD_NOT_ALLOWED
  if (zhi === 409) return CUO_WU_DAI_MA.RESOURCE_CONFLICT
  if (zhi === 413) return CUO_WU_DAI_MA.PAYLOAD_TOO_LARGE
  if (zhi === 429) return CUO_WU_DAI_MA.RATE_LIMITED
  if (zhi === 502) return CUO_WU_DAI_MA.UPSTREAM_NETWORK_ERROR
  if (zhi === 503) return CUO_WU_DAI_MA.SERVICE_UNAVAILABLE
  if (zhi === 504) return CUO_WU_DAI_MA.UPSTREAM_TIMEOUT
  return CUO_WU_DAI_MA.INTERNAL_ERROR
}
